# Generated by Django 5.2.3 on 2025-06-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='groups',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='session',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
