# Generated by Django 5.2.3 on 2025-06-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_customuser_profile_picture_quiz_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='groups',
            field=models.CharField(blank=True, choices=[('Group A', 'Group A'), ('Group B', 'Group B'), ('Group C', 'Group C'), ('Group D', 'Group D'), ('Group E', 'Group E'), ('Group F', 'Group F'), ('Group G', 'Group G'), ('Group H', 'Group H'), ('Group I', 'Group I'), ('Group J', 'Group J'), ('Group K', 'Group K'), ('Group L', 'Group L'), ('Group M', 'Group M'), ('Group N', 'Group N'), ('Group O', 'Group O'), ('Group P', 'Group P')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F'), ('G', 'Group G'), ('H', 'Group H'), ('I', 'Group I'), ('J', 'Group J'), ('K', 'Group K'), ('L', 'Group L'), ('M', 'Group M'), ('N', 'Group N'), ('O', 'Group O'), ('P', 'Group P')], max_length=5),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400')], default='100', max_length=10),
        ),
    ]
