# Generated by Django 5.2.3 on 2025-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_sheettask'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheettask',
            name='shared_with',
            field=models.ManyToManyField(blank=True, to='System.staffprofile'),
        ),
    ]
