# Generated by Django 5.2.3 on 2025-06-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
