# Generated by Django 5.2.3 on 2025-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
