# Generated by Django 5.2.3 on 2025-06-20 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_staffprofile_faculty_staffprofile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='courses_assigned',
        ),
        migrations.CreateModel(
            name='AssignedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.staffprofile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.semester')),
            ],
            options={
                'unique_together': {('staff', 'course', 'semester')},
            },
        ),
    ]
