# Generated by Django 5.2.3 on 2025-06-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_alter_question_option_c_alter_question_option_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheetquiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='googlesheetquiz',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='googlesheetquiz',
            name='title',
        ),
        migrations.AddField(
            model_name='googlesheetquiz',
            name='question_bank',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='System.questionbank'),
            preserve_default=False,
        ),
    ]
