# Generated by Django 5.2.3 on 2025-06-23 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_remove_googlesheetquiz_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('onhold', 'Onhold')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='googlesheetquiz',
            name='question_bank',
            field=models.ForeignKey(limit_choices_to={'is_general': True}, on_delete=django.db.models.deletion.CASCADE, to='System.questionbank'),
        ),
        migrations.CreateModel(
            name='StudentQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
