# Generated by Django 5.2.3 on 2025-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_semester_remove_staffprofile_courses_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='courses_assigned',
            field=models.ManyToManyField(blank=True, to='System.course'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
