# Generated by Django 5.2.3 on 2025-06-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_quiz_status_alter_googlesheetquiz_question_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='programme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
