# Generated by Django 5.2.3 on 2025-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_staffprofile_courses_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
